username: '15507947201'

password: '..qwe123'

# 演唱会详情页面URL
ticket_url: 'https://m.damai.cn/shows/item.html?itemId=768517208776&spm=a2o71.broadlist.list.d1.555bb966PO3u7B'

# 购买哪个站点
ticket_site: "佛山站"

# 场次日期
ticket_date: "2024-04-20"

# 票档
ticket_grade: "看台580元"

# 购买数量
ticket_num: 1

# 实名人名字, 没有相同姓氏只写姓即可，否则写完整姓名. 实名人数量需要与购票数量一致
real_names:
  - 李


